name: Generate Obsidian Context

on:
  push:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: .github/scripts

      - name: Generate Context File
        run: node generate-context.js
        working-directory: .github/scripts

      - name: Commit Context File
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add context.md
          git commit -m "Update context.md"
          git push || echo "No changes to commit"